### ISSUE TITLE
FATAL Error 

### ISSUE THREAD

**Issue by aryansabet** [markpatterson27/GitHub-Classroom-Check-For-Changes#2]
i found some fatal errors.

```text
Run echo "Checking for commits affecting .github/classroom/autograding.json .github/workflows/classroom.yml A6.Tests/MemoryTestTests.cs..."
fatal: ambiguous argument '1b8d2879abba79780a12f8ad7b8ab5f8d2d4c4e9..main': unknown revision or path not in the working tree.
Checking for commits affecting .github/classroom/autograding.json .github/workflows/classroom.yml A6.Tests/MemoryTestTests.cs...
Use '--' to separate paths from revisions, like this:
Running git log command: "git log 1b8d2879abba79780a12f8ad7b8ab5f8d2d4c4e9..main --perl-regexp --author='^((?!github-classroom\[bot\]).)*$' .github/classroom/autograding.json"
'git <command> [<revision>...] -- [<file>...]'
No changes found to .github/classroom/autograding.json
fatal: ambiguous argument '1b8d2879abba79780a12f8ad7b8ab5f8d2d4c4e9..main': unknown revision or path not in the working tree.
Running git log command: "git log 1b8d2879abba79780a12f8ad7b8ab5f8d2d4c4e9..main --perl-regexp --author='^((?!github-classroom\[bot\]).)*$' .github/classroom/autograding.json .github/workflows/classroom.yml"
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
No changes found to .github/workflows/classroom.yml
fatal: ambiguous argument '1b8d2879abba79780a12f8ad7b8ab5f8d2d4c4e9..main': unknown revision or path not in the working tree.
Running git log command: "git log 1b8d2879abba79780a12f8ad7b8ab5f8d2d4c4e9..main --perl-regexp --author='^((?!github-classroom\[bot\]).)*$' .github/classroom/autograding.json .github/workflows/classroom.yml A6.Tests/MemoryTestTests.cs"
Use '--' to separate paths from revisions, like this:
No changes found to A6.Tests/MemoryTestTests.cs
'git <command> [<revision>...] -- [<file>...]'
```

```yml
name: grader

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Autograding
        uses: education/autograding@v1

  change-check:
    uses: markpatterson27/GitHub-Classroom-Check-For-Changes/.github/workflows/change-check.yml@main
    with:
      paths: .github/classroom/autograding.json .github/workflows/classroom.yml A6.Tests/MemoryTestTests.cs

```
